'use client'

import Link from 'next/link'
import {
  Brain,
  Zap,
  Target,
  Calendar,
  TrendingUp,
  Shield,
  ArrowRight,
  CheckCircle2,
  Sparkles,
  Clock,
  AlertTriangle,
  BarChart3,
} from 'lucide-react'

const features = [
  {
    icon: Brain,
    title: 'AI Daily Briefing',
    description: 'Every session starts with a personalized briefing: your priorities, risks, and a tailored action plan — generated by Gemini AI.',
    iconBg: 'bg-purple-500/15',
    iconColor: 'text-purple-400',
  },
  {
    icon: AlertTriangle,
    title: 'Overload Detection',
    description: 'AI detects when your schedule is unrealistic and automatically tells you what to cut or reschedule before you miss deadlines.',
    iconBg: 'bg-red-500/15',
    iconColor: 'text-red-400',
  },
  {
    icon: Target,
    title: 'Smart Prioritization',
    description: 'Tasks are ranked by deadline urgency, difficulty, and impact — with clear reasoning for every single decision the AI makes.',
    iconBg: 'bg-teal-500/15',
    iconColor: 'text-teal-400',
  },
  {
    icon: Calendar,
    title: 'Auto-Schedule Generation',
    description: 'Get a time-blocked daily plan generated automatically based on your available hours, energy levels, and task priorities.',
    iconBg: 'bg-blue-500/15',
    iconColor: 'text-blue-400',
  },
  {
    icon: TrendingUp,
    title: 'Risk Prediction',
    description: 'Know in advance which tasks are at risk of being missed — before it is too late to do anything about it.',
    iconBg: 'bg-orange-500/15',
    iconColor: 'text-orange-400',
  },
  {
    icon: Shield,
    title: 'Adaptive Replanning',
    description: 'When life disrupts your plan, FlowMind AI instantly regenerates a realistic schedule around your new reality.',
    iconBg: 'bg-green-500/15',
    iconColor: 'text-green-400',
  },
]

const steps = [
  {
    number: '01',
    title: 'Add Your Tasks',
    description: 'Enter tasks with deadlines, estimated time, priority, and difficulty. Takes under 30 seconds per task.',
    icon: CheckCircle2,
  },
  {
    number: '02',
    title: 'AI Analyzes Your Workload',
    description: 'Gemini AI reads your entire task list, detects conflicts, predicts risks, and understands your schedule deeply.',
    icon: Brain,
  },
  {
    number: '03',
    title: 'Get Your Action Plan',
    description: 'Receive a prioritized schedule with clear reasoning for every recommendation. Know exactly what to do, when, and why.',
    icon: Zap,
  },
]

export default function LandingPage() {
  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#0A0A0F', color: '#F0F0FF', overflowX: 'hidden' }}>

      {/* ── Navbar ── */}
      <nav style={{ borderBottom: '1px solid rgba(255,255,255,0.06)', backgroundColor: 'rgba(10,10,15,0.9)', backdropFilter: 'blur(12px)', position: 'sticky', top: 0, zIndex: 50 }}>
        <div style={{ maxWidth: '1152px', margin: '0 auto', padding: '0 24px', height: '64px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <div style={{ width: '32px', height: '32px', borderRadius: '8px', background: 'linear-gradient(135deg, #6C63FF, #00D4AA)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
              <Brain style={{ width: '16px', height: '16px', color: 'white' }} />
            </div>
            <span style={{ fontSize: '18px', fontWeight: 700 }}>
              <span className="gradient-text">FlowMind</span>
              <span style={{ color: '#F0F0FF' }}> AI</span>
            </span>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Link href="/login" style={{ fontSize: '14px', color: '#8B8BA7', padding: '8px 16px', borderRadius: '8px', textDecoration: 'none', transition: 'color 0.2s' }}
              onMouseEnter={e => (e.currentTarget.style.color = '#F0F0FF')}
              onMouseLeave={e => (e.currentTarget.style.color = '#8B8BA7')}>
              Sign In
            </Link>
            <Link href="/login" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', backgroundColor: '#6C63FF', color: 'white', fontWeight: 600, fontSize: '14px', padding: '10px 20px', borderRadius: '10px', textDecoration: 'none', transition: 'background 0.2s' }}
              onMouseEnter={e => (e.currentTarget.style.backgroundColor = '#7B74FF')}
              onMouseLeave={e => (e.currentTarget.style.backgroundColor = '#6C63FF')}>
              Get Started <ArrowRight style={{ width: '14px', height: '14px' }} />
            </Link>
          </div>
        </div>
      </nav>

      {/* ── Hero Section ── */}
      <section style={{ width: '100%', paddingTop: '80px', paddingBottom: '64px' }}>
        <div style={{ maxWidth: '896px', margin: '0 auto', padding: '0 24px', textAlign: 'center' }}>

          {/* Badge */}
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', backgroundColor: 'rgba(108,99,255,0.1)', border: '1px solid rgba(108,99,255,0.25)', borderRadius: '999px', padding: '8px 16px', fontSize: '13px', color: '#a78bfa', marginBottom: '32px' }}>
            <Sparkles style={{ width: '14px', height: '14px' }} />
            Powered by Google Gemini 2.0 Flash
          </div>

          {/* Headline */}
          <h1 style={{ fontSize: 'clamp(2rem, 5vw, 3.75rem)', fontWeight: 900, lineHeight: 1.1, marginBottom: '24px', letterSpacing: '-0.02em' }}>
            Stop{' '}
            <span className="gradient-text">Missing</span>
            {' '}Deadlines.
            <br />
            Start{' '}
            <span className="gradient-text">Completing</span>
            {' '}Them.
          </h1>

          {/* Subheadline */}
          <p style={{ fontSize: 'clamp(1rem, 2vw, 1.125rem)', color: '#8B8BA7', maxWidth: '560px', margin: '0 auto 40px', lineHeight: 1.7 }}>
            FlowMind AI is your intelligent productivity partner that{' '}
            <strong style={{ color: '#F0F0FF' }}>thinks</strong>,{' '}
            <strong style={{ color: '#F0F0FF' }}>plans</strong>, and{' '}
            <strong style={{ color: '#F0F0FF' }}>adapts</strong>
            {' '}alongside you. Not just a reminder app — a real AI teammate.
          </p>

          {/* CTA Buttons */}
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '12px', justifyContent: 'center', alignItems: 'center' }}>
            <Link
              href="/login"
              id="cta-google-login"
              style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: '10px', background: 'linear-gradient(135deg, #6C63FF, #5B54E8)', color: 'white', fontWeight: 600, padding: '14px 28px', borderRadius: '12px', textDecoration: 'none', fontSize: '15px', transition: 'all 0.2s', boxShadow: '0 0 30px rgba(108,99,255,0.25)' }}>
              <svg style={{ width: '18px', height: '18px' }} viewBox="0 0 24 24">
                <path fill="#fff" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
                <path fill="#fff" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
                <path fill="#fff" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" />
                <path fill="#fff" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
              </svg>
              Continue with Google
            </Link>
            <Link
              href="/login?guest=true"
              id="cta-guest-login"
              style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: '8px', backgroundColor: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.12)', color: '#F0F0FF', fontWeight: 600, padding: '14px 28px', borderRadius: '12px', textDecoration: 'none', fontSize: '15px', transition: 'all 0.2s' }}>
              <Clock style={{ width: '18px', height: '18px', color: '#8B8BA7' }} />
              Try as Guest
            </Link>
          </div>

          <p style={{ fontSize: '13px', color: '#4A4A6A', marginTop: '20px' }}>Free forever. No credit card required.</p>
        </div>

        {/* Hero Visual — Mock AI Card */}
        <div style={{ maxWidth: '720px', margin: '56px auto 0', padding: '0 24px', position: 'relative' }}>
          {/* Bottom fade overlay */}
          <div style={{ position: 'absolute', left: '24px', right: '24px', bottom: 0, height: '80px', background: 'linear-gradient(to top, #0A0A0F, transparent)', zIndex: 2, pointerEvents: 'none' }} />
          <div className="glass" style={{ borderRadius: '16px', padding: '24px', border: '1px solid rgba(108,99,255,0.2)', boxShadow: '0 0 30px rgba(108,99,255,0.15)' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <div style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: '#00D4AA', animation: 'pulse 2s infinite' }} />
                <span style={{ fontSize: '13px', fontWeight: 500, color: '#8B8BA7' }}>AI Command Center</span>
              </div>
              <span style={{ fontSize: '11px', color: '#a78bfa', backgroundColor: 'rgba(108,99,255,0.1)', padding: '4px 10px', borderRadius: '999px', border: '1px solid rgba(108,99,255,0.2)' }}>Gemini Active</span>
            </div>
            <div style={{ backgroundColor: '#1C1C27', borderRadius: '12px', padding: '16px', marginBottom: '12px', border: '1px solid rgba(255,255,255,0.05)' }}>
              <p style={{ fontSize: '11px', color: '#8B8BA7', marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.08em' }}>AI Analysis</p>
              <p style={{ fontSize: '13px', color: '#F0F0FF', lineHeight: 1.6 }}>
                ⚠️ <strong>Overload detected.</strong> You have 14 hours of work but only 6 hours available today.
                I&apos;ve reprioritized your tasks — focus on{' '}
                <span style={{ color: '#a78bfa', fontWeight: 500 }}>&quot;Client Presentation&quot;</span> first.
                Consider moving &quot;Research Report&quot; to tomorrow.
              </p>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '10px' }}>
              {[['5', 'Tasks Today'], ['2.5h', 'Focus Time'], ['87%', 'On Track']].map(([val, label]) => (
                <div key={label} style={{ backgroundColor: '#1C1C27', borderRadius: '10px', padding: '12px', textAlign: 'center', border: '1px solid rgba(255,255,255,0.05)' }}>
                  <div className="gradient-text" style={{ fontSize: '20px', fontWeight: 700 }}>{val}</div>
                  <div style={{ fontSize: '11px', color: '#8B8BA7', marginTop: '2px' }}>{label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── Stats Bar ── */}
      <section style={{ width: '100%', borderTop: '1px solid rgba(255,255,255,0.06)', borderBottom: '1px solid rgba(255,255,255,0.06)', padding: '48px 0' }}>
        <div style={{ maxWidth: '768px', margin: '0 auto', padding: '0 24px', display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '24px', textAlign: 'center' }}>
          {[
            { value: '10K+', label: 'Tasks Completed' },
            { value: '94%', label: 'On-Time Rate' },
            { value: '3x', label: 'Productivity Boost' },
          ].map((stat) => (
            <div key={stat.label}>
              <div className="gradient-text" style={{ fontSize: 'clamp(1.75rem, 4vw, 2.25rem)', fontWeight: 900 }}>{stat.value}</div>
              <div style={{ fontSize: '14px', color: '#8B8BA7', marginTop: '4px' }}>{stat.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── Features Grid ── */}
      <section style={{ width: '100%', padding: '80px 0' }}>
        <div style={{ maxWidth: '1152px', margin: '0 auto', padding: '0 24px' }}>
          <div style={{ textAlign: 'center', marginBottom: '56px' }}>
            <h2 style={{ fontSize: 'clamp(1.75rem, 4vw, 2.5rem)', fontWeight: 900, marginBottom: '16px' }}>
              Not a todo list.{' '}
              <span className="gradient-text">An AI partner.</span>
            </h2>
            <p style={{ color: '#8B8BA7', fontSize: '16px', maxWidth: '480px', margin: '0 auto' }}>
              Every feature is built around one goal: helping you complete work, not just track it.
            </p>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '20px' }}>
            {features.map((feature) => (
              <div key={feature.title} className="card-hover">
                <div style={{ width: '44px', height: '44px', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '16px' }} className={feature.iconBg}>
                  <feature.icon style={{ width: '22px', height: '22px' }} className={feature.iconColor} />
                </div>
                <h3 style={{ fontSize: '16px', fontWeight: 700, marginBottom: '8px', color: '#F0F0FF' }}>{feature.title}</h3>
                <p style={{ fontSize: '13px', color: '#8B8BA7', lineHeight: 1.65 }}>{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── How It Works ── */}
      <section style={{ width: '100%', padding: '80px 0', background: 'linear-gradient(to bottom, transparent, rgba(108,99,255,0.03), transparent)' }}>
        <div style={{ maxWidth: '768px', margin: '0 auto', padding: '0 24px' }}>
          <div style={{ textAlign: 'center', marginBottom: '48px' }}>
            <h2 style={{ fontSize: 'clamp(1.75rem, 4vw, 2.5rem)', fontWeight: 900, marginBottom: '12px' }}>
              How it <span className="gradient-text">works</span>
            </h2>
            <p style={{ color: '#8B8BA7', fontSize: '16px' }}>Three steps from overwhelmed to in control.</p>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            {steps.map((step) => (
              <div key={step.number} className="glass" style={{ display: 'flex', alignItems: 'flex-start', gap: '20px', padding: '24px', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.06)', transition: 'border-color 0.3s' }}
                onMouseEnter={e => (e.currentTarget.style.borderColor = 'rgba(108,99,255,0.25)')}
                onMouseLeave={e => (e.currentTarget.style.borderColor = 'rgba(255,255,255,0.06)')}>
                <div style={{ flexShrink: 0, width: '52px', height: '52px', borderRadius: '12px', background: 'linear-gradient(135deg, rgba(108,99,255,0.15), rgba(0,212,170,0.15))', display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px solid rgba(108,99,255,0.2)' }}>
                  <span className="gradient-text" style={{ fontSize: '18px', fontWeight: 900 }}>{step.number}</span>
                </div>
                <div>
                  <h3 style={{ fontSize: '18px', fontWeight: 700, marginBottom: '6px', color: '#F0F0FF' }}>{step.title}</h3>
                  <p style={{ color: '#8B8BA7', lineHeight: 1.65, fontSize: '14px' }}>{step.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Final CTA ── */}
      <section style={{ width: '100%', padding: '80px 0' }}>
        <div style={{ maxWidth: '640px', margin: '0 auto', padding: '0 24px' }}>
          <div style={{ padding: '1px', borderRadius: '20px', background: 'linear-gradient(135deg, #6C63FF, #00D4AA)' }}>
            <div style={{ backgroundColor: '#0A0A0F', borderRadius: '19px', padding: '48px 40px', textAlign: 'center' }}>
              <div style={{ width: '48px', height: '48px', borderRadius: '12px', backgroundColor: 'rgba(108,99,255,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 24px' }}>
                <BarChart3 style={{ width: '24px', height: '24px', color: '#a78bfa' }} />
              </div>
              <h2 style={{ fontSize: 'clamp(1.5rem, 3.5vw, 2rem)', fontWeight: 900, marginBottom: '16px' }}>
                Ready to stop{' '}
                <span className="gradient-text-warm">procrastinating?</span>
              </h2>
              <p style={{ color: '#8B8BA7', marginBottom: '32px', lineHeight: 1.65, fontSize: '15px' }}>
                Join students and professionals who use FlowMind AI to stay ahead of their deadlines — with an AI that actually helps them complete tasks.
              </p>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '12px', justifyContent: 'center' }}>
                <Link
                  href="/login"
                  id="cta-bottom"
                  style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', backgroundColor: '#6C63FF', color: 'white', fontWeight: 600, padding: '12px 28px', borderRadius: '10px', textDecoration: 'none', fontSize: '15px', transition: 'all 0.2s' }}>
                  Start for Free <ArrowRight style={{ width: '16px', height: '16px' }} />
                </Link>
                <Link
                  href="/login?guest=true"
                  style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', backgroundColor: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.12)', color: '#F0F0FF', fontWeight: 600, padding: '12px 28px', borderRadius: '10px', textDecoration: 'none', fontSize: '15px', transition: 'all 0.2s' }}>
                  <Clock style={{ width: '16px', height: '16px' }} />
                  Try without signup
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer style={{ width: '100%', borderTop: '1px solid rgba(255,255,255,0.06)', padding: '32px 0' }}>
        <div style={{ maxWidth: '1152px', margin: '0 auto', padding: '0 24px', display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: '16px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <div style={{ width: '24px', height: '24px', borderRadius: '6px', background: 'linear-gradient(135deg, #6C63FF, #00D4AA)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <Brain style={{ width: '12px', height: '12px', color: 'white' }} />
            </div>
            <span style={{ fontSize: '14px', fontWeight: 600 }}>
              <span className="gradient-text">FlowMind</span> AI
            </span>
          </div>
          <p style={{ fontSize: '13px', color: '#4A4A6A', textAlign: 'center' }}>
            Built with Google Gemini AI + Firebase · Coding Ninjas × Google Vibe2Ship Hackathon 2026
          </p>
          <div style={{ fontSize: '12px', color: '#4A4A6A' }}>
            Powered by <span style={{ color: '#8B8BA7', fontWeight: 500 }}>Gemini · Firebase · Firestore</span>
          </div>
        </div>
      </footer>
    </div>
  )
}
