'use client'

import Link from 'next/link'
import {
  Brain,
  Zap,
  Target,
  Calendar,
  TrendingUp,
  Shield,
  ArrowRight,
  CheckCircle2,
  Sparkles,
  Clock,
  AlertTriangle,
  BarChart3,
} from 'lucide-react'
import { cn } from '@/lib/utils/cn'

const features = [
  {
    icon: Brain,
    title: 'AI Daily Briefing',
    description: 'Every session starts with a personalized briefing: your priorities, risks, and a tailored action plan — generated by Gemini AI.',
    iconBg: 'bg-purple-500/15',
    iconColor: 'text-purple-400',
  },
  {
    icon: AlertTriangle,
    title: 'Overload Detection',
    description: 'AI detects when your schedule is unrealistic and automatically tells you what to cut or reschedule before you miss deadlines.',
    iconBg: 'bg-red-500/15',
    iconColor: 'text-red-400',
  },
  {
    icon: Target,
    title: 'Smart Prioritization',
    description: 'Tasks are ranked by deadline urgency, difficulty, and impact — with clear reasoning for every single decision the AI makes.',
    iconBg: 'bg-teal-500/15',
    iconColor: 'text-teal-400',
  },
  {
    icon: Calendar,
    title: 'Auto-Schedule Generation',
    description: 'Get a time-blocked daily plan generated automatically based on your available hours, energy levels, and task priorities.',
    iconBg: 'bg-blue-500/15',
    iconColor: 'text-blue-400',
  },
  {
    icon: TrendingUp,
    title: 'Risk Prediction',
    description: 'Know in advance which tasks are at risk of being missed — before it is too late to do anything about it.',
    iconBg: 'bg-orange-500/15',
    iconColor: 'text-orange-400',
  },
  {
    icon: Shield,
    title: 'Adaptive Replanning',
    description: 'When life disrupts your plan, FlowMind AI instantly regenerates a realistic schedule around your new reality.',
    iconBg: 'bg-green-500/15',
    iconColor: 'text-green-400',
  },
]

const steps = [
  {
    number: '01',
    title: 'Add Your Tasks',
    description: 'Enter tasks with deadlines, estimated time, priority, and difficulty. Takes under 30 seconds per task.',
    icon: CheckCircle2,
  },
  {
    number: '02',
    title: 'AI Analyzes Your Workload',
    description: 'Gemini AI reads your entire task list, detects conflicts, predicts risks, and understands your schedule deeply.',
    icon: Brain,
  },
  {
    number: '03',
    title: 'Get Your Action Plan',
    description: 'Receive a prioritized schedule with clear reasoning for every recommendation. Know exactly what to do, when, and why.',
    icon: Zap,
  },
]

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0F] text-[#F0F0FF] overflow-x-hidden flex flex-col font-sans">

      {/* Navbar */}
      <nav className="border-b border-white/5 bg-[#0A0A0F]/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="w-full max-w-6xl mx-auto px-6 lg:px-8 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-[#6C63FF] to-[#00D4AA] flex items-center justify-center shadow-glow-teal flex-shrink-0">
              <Brain className="w-5 h-5 text-white" />
            </div>
            <span className="text-xl font-bold tracking-tight">
              <span className="gradient-text">FlowMind</span>
              <span className="text-[#F0F0FF]"> AI</span>
            </span>
          </div>
          <div className="flex items-center gap-4">
            <Link href="/login" className="text-sm font-medium text-[#8B8BA7] hover:text-[#F0F0FF] transition-colors hidden sm:block">
              Sign In
            </Link>
            <Link href="/login" className="inline-flex items-center justify-center gap-2 bg-[#6C63FF] hover:bg-[#7B74FF] text-white font-semibold text-sm px-6 h-10 rounded-lg transition-colors shadow-glow-purple">
              Get Started <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </nav>

      <main className="flex-1 w-full">
        {/* Hero Section */}
        <section className="w-full max-w-6xl mx-auto px-6 lg:px-8 pt-24 pb-16 sm:pt-32 sm:pb-24 flex flex-col items-center text-center">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 bg-[#6C63FF]/10 border border-[#6C63FF]/20 rounded-full px-5 py-2.5 text-xs sm:text-sm text-[#a78bfa] mb-10 font-medium">
            <Sparkles className="w-4 h-4" />
            Powered by Google Gemini 2.0 Flash
          </div>

          {/* Headline */}
          <h1 className="text-[clamp(2.5rem,7vw,4.5rem)] font-black leading-[1.05] mb-8 tracking-tight max-w-4xl mx-auto">
            Stop <span className="gradient-text">Missing</span> Deadlines.<br />
            Start <span className="gradient-text">Completing</span> Them.
          </h1>

          {/* Subheadline */}
          <p className="text-base sm:text-lg md:text-xl text-[#8B8BA7] max-w-2xl mx-auto mb-12 leading-relaxed">
            FlowMind AI is your intelligent productivity partner that <strong className="text-[#F0F0FF] font-semibold">thinks</strong>, <strong className="text-[#F0F0FF] font-semibold">plans</strong>, and <strong className="text-[#F0F0FF] font-semibold">adapts</strong> alongside you. Not just a reminder app — a real AI teammate.
          </p>

          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-5 w-full max-w-lg mx-auto">
            <Link
              href="/login"
              className="flex-1 w-full h-14 inline-flex items-center justify-center gap-2 bg-gradient-to-r from-[#6C63FF] to-[#5B54E8] hover:from-[#7B74FF] hover:to-[#6C63FF] text-white font-bold rounded-xl transition-all duration-200 shadow-glow-purple text-base"
            >
              <svg className="w-5 h-5 flex-shrink-0" viewBox="0 0 24 24">
                <path fill="#fff" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
                <path fill="#fff" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
                <path fill="#fff" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" />
                <path fill="#fff" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
              </svg>
              Google Login
            </Link>
            <Link
              href="/login?guest=true"
              className="flex-1 w-full h-14 inline-flex items-center justify-center gap-2 bg-[#13131A] hover:bg-[#1C1C27] border border-[#2A2A3A] text-[#F0F0FF] font-bold rounded-xl transition-all duration-200 text-base"
            >
              <Clock className="w-5 h-5 text-[#8B8BA7]" />
              Guest Login
            </Link>
          </div>
          <p className="text-sm text-[#4A4A6A] mt-6">Free forever. No credit card required.</p>
        </section>

        {/* Hero Visual */}
        <section className="w-full max-w-6xl mx-auto px-6 lg:px-8 pb-24 flex justify-center">
          <div className="w-full max-w-4xl relative">
            <div className="absolute left-0 right-0 bottom-0 h-24 bg-gradient-to-t from-[#0A0A0F] to-transparent z-10 pointer-events-none" />
            <div className="glass rounded-2xl p-6 sm:p-8 border border-[#6C63FF]/20 shadow-card">
              <div className="flex items-center justify-between gap-4 mb-6">
                <div className="flex items-center gap-3">
                  <div className="w-2.5 h-2.5 rounded-full bg-[#00D4AA] animate-pulse" />
                  <span className="text-sm font-semibold text-[#8B8BA7] uppercase tracking-wider">AI Command Center</span>
                </div>
                <span className="text-xs font-bold text-[#a78bfa] bg-[#6C63FF]/10 px-3 py-1.5 rounded-full border border-[#6C63FF]/20">
                  Gemini Active
                </span>
              </div>
              <div className="bg-[#1C1C27] rounded-xl p-5 mb-6 border border-white/5">
                <p className="text-xs text-[#8B8BA7] mb-3 uppercase tracking-wider font-bold">AI Analysis</p>
                <p className="text-sm sm:text-base text-[#F0F0FF] leading-relaxed">
                  ⚠️ <strong>Overload detected.</strong> You have 14 hours of work but only 6 hours available today.
                  I&apos;ve reprioritized your tasks — focus on <span className="text-[#a78bfa] font-bold">&quot;Client Presentation&quot;</span> first.
                  Consider moving &quot;Research Report&quot; to tomorrow.
                </p>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
                {[
                  ['5', 'Tasks Today'],
                  ['2.5h', 'Focus Time'],
                  ['87%', 'On Track']
                ].map(([val, label]) => (
                  <div key={label} className="bg-[#1C1C27] rounded-xl p-5 text-center border border-white/5 flex flex-col items-center justify-center">
                    <div className="gradient-text text-2xl font-black mb-1">{val}</div>
                    <div className="text-xs font-semibold text-[#8B8BA7]">{label}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Stats Bar */}
        <section className="w-full border-y border-[#2A2A3A] py-16 bg-[#0A0A0F]/50">
          <div className="w-full max-w-6xl mx-auto px-6 lg:px-8">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-10 text-center">
              {[
                { value: '10K+', label: 'Tasks Completed' },
                { value: '94%', label: 'On-Time Rate' },
                { value: '3x', label: 'Productivity Boost' },
              ].map((stat) => (
                <div key={stat.label} className="flex flex-col items-center justify-center">
                  <div className="gradient-text text-4xl sm:text-5xl font-black mb-2">{stat.value}</div>
                  <div className="text-sm font-semibold text-[#8B8BA7] tracking-wide uppercase">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Features Grid */}
        <section className="w-full py-32">
          <div className="w-full max-w-6xl mx-auto px-6 lg:px-8">
            <div className="text-center mb-16 max-w-3xl mx-auto">
              <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black mb-6 leading-tight">
                Not a todo list. <span className="gradient-text">An AI partner.</span>
              </h2>
              <p className="text-base sm:text-lg text-[#8B8BA7] leading-relaxed">
                Every feature is built around one goal: helping you complete work, not just track it.
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {features.map((feature) => (
                <div key={feature.title} className="card-hover flex flex-col h-full bg-[#13131A] border border-[#2A2A3A] rounded-2xl p-8 transition-all duration-300 shadow-card">
                  <div className={cn('w-12 h-12 rounded-xl flex items-center justify-center mb-6', feature.iconBg)}>
                    <feature.icon className={cn('w-6 h-6', feature.iconColor)} />
                  </div>
                  <h3 className="text-lg font-bold mb-3 text-[#F0F0FF]">{feature.title}</h3>
                  <p className="text-sm text-[#8B8BA7] leading-relaxed flex-1">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* How It Works */}
        <section className="w-full py-32 bg-gradient-to-b from-transparent via-[#6C63FF]/5 to-transparent">
          <div className="w-full max-w-6xl mx-auto px-6 lg:px-8">
            <div className="text-center mb-16 max-w-3xl mx-auto">
              <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black mb-6 leading-tight">
                How it <span className="gradient-text">works</span>
              </h2>
              <p className="text-base sm:text-lg text-[#8B8BA7] leading-relaxed">
                Three steps from overwhelmed to in control.
              </p>
            </div>
            <div className="flex flex-col gap-8 max-w-3xl mx-auto">
              {steps.map((step) => (
                <div key={step.number} className="glass flex items-start sm:items-center gap-6 p-8 rounded-2xl border border-[#2A2A3A] transition-all duration-300 hover:border-[#6C63FF]/30 shadow-card">
                  <div className="flex-shrink-0 w-14 h-14 rounded-xl bg-gradient-to-br from-[#6C63FF]/15 to-[#00D4AA]/15 flex items-center justify-center border border-[#6C63FF]/20">
                    <span className="gradient-text text-xl font-black">{step.number}</span>
                  </div>
                  <div className="flex-1 min-w-0">
                    <h3 className="text-lg sm:text-xl font-bold mb-2 text-[#F0F0FF]">{step.title}</h3>
                    <p className="text-sm text-[#8B8BA7] leading-relaxed">{step.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Final CTA */}
        <section className="w-full py-32">
          <div className="w-full max-w-6xl mx-auto px-6 lg:px-8">
            <div className="max-w-4xl mx-auto p-[1px] rounded-3xl bg-gradient-to-r from-[#6C63FF] to-[#00D4AA]">
              <div className="bg-[#0A0A0F] rounded-[23px] py-20 px-8 sm:px-12 text-center flex flex-col items-center shadow-glow-purple">
                <div className="w-16 h-16 rounded-2xl bg-[#6C63FF]/15 flex items-center justify-center mb-8 border border-[#6C63FF]/20">
                  <BarChart3 className="w-8 h-8 text-[#a78bfa]" />
                </div>
                <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black mb-6 leading-tight">
                  Ready to stop <span className="gradient-text-warm">procrastinating?</span>
                </h2>
                <p className="text-base sm:text-lg text-[#8B8BA7] mb-12 max-w-2xl leading-relaxed">
                  Join students and professionals who use FlowMind AI to stay ahead of their deadlines — with an AI that actually helps them complete tasks.
                </p>
                <div className="flex flex-col sm:flex-row items-center justify-center gap-5 w-full max-w-lg mx-auto">
                  <Link
                    href="/login"
                    className="flex-1 w-full h-14 inline-flex items-center justify-center gap-2 bg-gradient-to-r from-[#6C63FF] to-[#5B54E8] hover:from-[#7B74FF] hover:to-[#6C63FF] text-white font-bold rounded-xl transition-all duration-200 shadow-glow-purple text-base"
                  >
                    Start for Free <ArrowRight className="w-5 h-5" />
                  </Link>
                  <Link
                    href="/login?guest=true"
                    className="flex-1 w-full h-14 inline-flex items-center justify-center gap-2 bg-[#13131A] hover:bg-[#1C1C27] border border-[#2A2A3A] text-[#F0F0FF] font-bold rounded-xl transition-all duration-200 text-base"
                  >
                    <Clock className="w-5 h-5 text-[#8B8BA7]" />
                    Try as Guest
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="w-full border-t border-[#2A2A3A] py-16 bg-[#0A0A0F]">
        <div className="w-full max-w-6xl mx-auto px-6 lg:px-8 flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#6C63FF] to-[#00D4AA] flex items-center justify-center flex-shrink-0">
              <Brain className="w-4 h-4 text-white" />
            </div>
            <span className="text-base font-bold tracking-tight">
              <span className="gradient-text">FlowMind</span> AI
            </span>
          </div>
          <p className="text-xs text-[#8B8BA7] text-center font-medium">
            Built with Google Gemini AI + Firebase · Coding Ninjas × Google Vibe2Ship Hackathon 2026
          </p>
          <div className="text-xs font-semibold">
            <span className="text-[#4A4A6A]">Powered by </span>
            <span className="text-[#8B8BA7]">Gemini · Firebase · Firestore</span>
          </div>
        </div>
      </footer>
    </div>
  )
}
