'use client'

import Link from 'next/link'
import {
  Brain,
  Zap,
  Target,
  Calendar,
  TrendingUp,
  Shield,
  ArrowRight,
  CheckCircle2,
  Sparkles,
  Clock,
  AlertTriangle,
  BarChart3,
} from 'lucide-react'

const features = [
  {
    icon: Brain,
    title: 'AI Daily Briefing',
    description: 'Every session starts with a personalized briefing: your priorities, risks, and a tailored action plan — generated by Gemini AI.',
    iconBg: 'bg-purple-500/15',
    iconColor: 'text-purple-400',
  },
  {
    icon: AlertTriangle,
    title: 'Overload Detection',
    description: 'AI detects when your schedule is unrealistic and automatically tells you what to cut or reschedule before you miss deadlines.',
    iconBg: 'bg-red-500/15',
    iconColor: 'text-red-400',
  },
  {
    icon: Target,
    title: 'Smart Prioritization',
    description: 'Tasks are ranked by deadline urgency, difficulty, and impact — with clear reasoning for every single decision the AI makes.',
    iconBg: 'bg-teal-500/15',
    iconColor: 'text-teal-400',
  },
  {
    icon: Calendar,
    title: 'Auto-Schedule Generation',
    description: 'Get a time-blocked daily plan generated automatically based on your available hours, energy levels, and task priorities.',
    iconBg: 'bg-blue-500/15',
    iconColor: 'text-blue-400',
  },
  {
    icon: TrendingUp,
    title: 'Risk Prediction',
    description: 'Know in advance which tasks are at risk of being missed — before it is too late to do anything about it.',
    iconBg: 'bg-orange-500/15',
    iconColor: 'text-orange-400',
  },
  {
    icon: Shield,
    title: 'Adaptive Replanning',
    description: 'When life disrupts your plan, FlowMind AI instantly regenerates a realistic schedule around your new reality.',
    iconBg: 'bg-green-500/15',
    iconColor: 'text-green-400',
  },
]

const steps = [
  {
    number: '01',
    title: 'Add Your Tasks',
    description: 'Enter tasks with deadlines, estimated time, priority, and difficulty. Takes under 30 seconds per task.',
    icon: CheckCircle2,
  },
  {
    number: '02',
    title: 'AI Analyzes Your Workload',
    description: 'Gemini AI reads your entire task list, detects conflicts, predicts risks, and understands your schedule deeply.',
    icon: Brain,
  },
  {
    number: '03',
    title: 'Get Your Action Plan',
    description: 'Receive a prioritized schedule with clear reasoning for every recommendation. Know exactly what to do, when, and why.',
    icon: Zap,
  },
]

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0F] text-[#F0F0FF] overflow-x-hidden flex flex-col">

      {/* Navbar */}
      <nav className="border-b border-white/5 bg-[#0A0A0F]/90 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#6C63FF] to-[#00D4AA] flex items-center justify-center flex-shrink-0">
              <Brain className="w-4 h-4 text-white" />
            </div>
            <span className="text-lg font-bold">
              <span className="gradient-text">FlowMind</span>
              <span className="text-[#F0F0FF]"> AI</span>
            </span>
          </div>
          <div className="flex items-center gap-2">
            <Link href="/login" className="text-sm text-[#8B8BA7] hover:text-[#F0F0FF] px-4 py-2 rounded-lg transition-colors">
              Sign In
            </Link>
            <Link href="/login" className="inline-flex items-center gap-2 bg-[#6C63FF] hover:bg-[#7B74FF] text-white font-semibold text-sm px-5 py-2.5 rounded-xl transition-colors">
              Get Started <ArrowRight className="w-3.5 h-3.5" />
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="w-full pt-16 pb-12 sm:pt-20 sm:pb-16 flex justify-center">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center flex flex-col items-center">

          {/* Badge */}
          <div className="inline-flex items-center gap-2 bg-[#6C63FF]/10 border border-[#6C63FF]/25 rounded-full px-4 py-2 text-xs text-[#a78bfa] mb-8 font-medium">
            <Sparkles className="w-3.5 h-3.5" />
            Powered by Google Gemini 2.0 Flash
          </div>

          {/* Headline */}
          <h1 className="text-[clamp(2.25rem,6vw,4rem)] font-black leading-[1.1] mb-6 tracking-tight max-w-3xl">
            Stop <span className="gradient-text">Missing</span> Deadlines.
            <br />
            Start <span className="gradient-text">Completing</span> Them.
          </h1>

          {/* Subheadline */}
          <p className="text-sm sm:text-base md:text-lg text-[#8B8BA7] max-w-2xl mx-auto mb-10 leading-relaxed">
            FlowMind AI is your intelligent productivity partner that <strong className="text-[#F0F0FF] font-semibold">thinks</strong>, <strong className="text-[#F0F0FF] font-semibold">plans</strong>, and <strong className="text-[#F0F0FF] font-semibold">adapts</strong> alongside you. Not just a reminder app — a real AI teammate.
          </p>

          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center w-full max-w-md mx-auto">
            <Link
              href="/login"
              id="cta-google-login"
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2.5 bg-gradient-to-r from-[#6C63FF] to-[#5B54E8] hover:from-[#7B74FF] hover:to-[#6C63FF] text-white font-semibold px-7 py-3.5 rounded-xl transition-all duration-200 shadow-[0_0_30px_rgba(108,99,255,0.25)] text-sm sm:text-base"
            >
              <svg className="w-4.5 h-4.5" viewBox="0 0 24 24">
                <path fill="#fff" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
                <path fill="#fff" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
                <path fill="#fff" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" />
                <path fill="#fff" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
              </svg>
              Continue with Google
            </Link>
            <Link
              href="/login?guest=true"
              id="cta-guest-login"
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-white/5 hover:bg-white/10 border border-white/10 text-[#F0F0FF] font-semibold px-7 py-3.5 rounded-xl transition-all duration-200 text-sm sm:text-base"
            >
              <Clock className="w-4.5 h-4.5 text-[#8B8BA7]" />
              Try as Guest
            </Link>
          </div>

          <p className="text-xs text-[#4A4A6A] mt-5">Free forever. No credit card required.</p>
        </div>
      </section>

      {/* Hero Visual — Mock AI Card */}
      <section className="w-full pb-16 flex justify-center">
        <div className="max-w-4xl w-full mx-auto px-4 sm:px-6 lg:px-8 relative">
          <div className="absolute left-4 right-4 bottom-0 h-20 bg-gradient-to-t from-[#0A0A0F] to-transparent z-10 pointer-events-none" />
          <div className="glass rounded-2xl p-6 border border-[#6C63FF]/20 shadow-[0_0_30px_rgba(108,99,255,0.15)]">
            <div className="flex flex-wrap items-center justify-between gap-2 mb-4">
              <div className="flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-[#00D4AA] animate-pulse" />
                <span className="text-xs font-medium text-[#8B8BA7]">AI Command Center</span>
              </div>
              <span className="text-[10px] text-[#a78bfa] bg-[#6C63FF]/10 px-2.5 py-1 rounded-full border border-[#6C63FF]/20">Gemini Active</span>
            </div>
            <div className="bg-[#1C1C27] rounded-xl p-4 mb-4 border border-white/5">
              <p className="text-[10px] text-[#8B8BA7] mb-2 uppercase tracking-wider font-semibold">AI Analysis</p>
              <p className="text-xs sm:text-sm text-[#F0F0FF] leading-relaxed">
                ⚠️ <strong>Overload detected.</strong> You have 14 hours of work but only 6 hours available today.
                I&apos;ve reprioritized your tasks — focus on <span className="text-[#a78bfa] font-medium">&quot;Client Presentation&quot;</span> first.
                Consider moving &quot;Research Report&quot; to tomorrow.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {[
                ['5', 'Tasks Today'],
                ['2.5h', 'Focus Time'],
                ['87%', 'On Track']
              ].map(([val, label]) => (
                <div key={label} className="bg-[#1C1C27] rounded-xl p-3 text-center border border-white/5">
                  <div className="gradient-text text-xl font-bold">{val}</div>
                  <div className="text-[10px] text-[#8B8BA7] mt-0.5">{label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Stats Bar */}
      <section className="w-full border-y border-white/5 py-12 bg-[#0A0A0F] flex justify-center">
        <div className="max-w-4xl w-full mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-1 sm:grid-cols-3 gap-8 text-center">
          {[
            { value: '10K+', label: 'Tasks Completed' },
            { value: '94%', label: 'On-Time Rate' },
            { value: '3x', label: 'Productivity Boost' },
          ].map((stat) => (
            <div key={stat.label} className="flex flex-col items-center">
              <div className="gradient-text text-3xl sm:text-4xl font-black">{stat.value}</div>
              <div className="text-xs sm:text-sm text-[#8B8BA7] mt-1">{stat.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Features Grid */}
      <section className="w-full py-20 flex justify-center">
        <div className="max-w-6xl w-full mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-black mb-4">
              Not a todo list. <span className="gradient-text">An AI partner.</span>
            </h2>
            <p className="text-sm sm:text-base text-[#8B8BA7] max-w-lg mx-auto leading-relaxed">
              Every feature is built around one goal: helping you complete work, not just track it.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature) => (
              <div key={feature.title} className="card-hover flex flex-col h-full bg-[#13131A] border border-[#2A2A3A] rounded-2xl p-6 transition-all duration-300">
                <div className={`w-11 h-11 rounded-xl flex items-center justify-center mb-4 ${feature.iconBg}`}>
                  <feature.icon className={`w-5 h-5 ${feature.iconColor}`} />
                </div>
                <h3 className="text-base font-bold mb-2 text-[#F0F0FF]">{feature.title}</h3>
                <p className="text-xs sm:text-sm text-[#8B8BA7] leading-relaxed flex-1">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="w-full py-20 bg-gradient-to-b from-transparent via-[#6C63FF]/3 to-transparent flex justify-center">
        <div className="max-w-3xl w-full mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-black mb-4">
              How it <span className="gradient-text">works</span>
            </h2>
            <p className="text-sm sm:text-base text-[#8B8BA7]">Three steps from overwhelmed to in control.</p>
          </div>

          <div className="flex flex-col gap-4">
            {steps.map((step) => (
              <div key={step.number} className="glass flex items-start gap-5 p-6 rounded-2xl border border-white/5 transition-all duration-300 hover:border-[#6C63FF]/25">
                <div className="flex-shrink-0 w-12 h-12 rounded-xl bg-gradient-to-br from-[#6C63FF]/15 to-[#00D4AA]/15 flex items-center justify-center border border-[#6C63FF]/20">
                  <span className="gradient-text text-base font-extrabold">{step.number}</span>
                </div>
                <div className="min-w-0">
                  <h3 className="text-base sm:text-lg font-bold mb-1.5 text-[#F0F0FF]">{step.title}</h3>
                  <p className="text-xs sm:text-sm text-[#8B8BA7] leading-relaxed">{step.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="w-full py-20 flex justify-center">
        <div className="max-w-2xl w-full mx-auto px-4 sm:px-6 lg:px-8">
          <div className="p-[1px] rounded-2xl bg-gradient-to-r from-[#6C63FF] to-[#00D4AA]">
            <div className="bg-[#0A0A0F] rounded-[15px] py-12 px-6 sm:px-10 text-center flex flex-col items-center">
              <div className="w-12 h-12 rounded-xl bg-[#6C63FF]/15 flex items-center justify-center mb-6">
                <BarChart3 className="w-6 h-6 text-[#a78bfa]" />
              </div>
              <h2 className="text-2xl sm:text-3xl font-black mb-4">
                Ready to stop <span className="gradient-text-warm">procrastinating?</span>
              </h2>
              <p className="text-xs sm:text-sm text-[#8B8BA7] mb-8 max-w-md leading-relaxed">
                Join students and professionals who use FlowMind AI to stay ahead of their deadlines — with an AI that actually helps them complete tasks.
              </p>
              <div className="flex flex-col sm:flex-row gap-3 justify-center w-full max-w-sm">
                <Link
                  href="/login"
                  id="cta-bottom"
                  className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-[#6C63FF] hover:bg-[#7B74FF] text-white font-semibold px-6 py-3 rounded-xl transition-colors text-sm"
                >
                  Start for Free <ArrowRight className="w-4 h-4" />
                </Link>
                <Link
                  href="/login?guest=true"
                  className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-white/5 hover:bg-white/10 border border-white/10 text-[#F0F0FF] font-semibold px-6 py-3 rounded-xl transition-colors text-sm"
                >
                  <Clock className="w-4 h-4 text-[#8B8BA7]" />
                  Try without signup
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="w-full border-t border-white/5 py-8 mt-auto flex justify-center bg-[#0A0A0F]">
        <div className="max-w-6xl w-full mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded bg-gradient-to-br from-[#6C63FF] to-[#00D4AA] flex items-center justify-center flex-shrink-0">
              <Brain className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="text-sm font-semibold">
              <span className="gradient-text">FlowMind</span> AI
            </span>
          </div>
          <p className="text-[11px] text-[#4A4A6A] text-center sm:text-left">
            Built with Google Gemini AI + Firebase · Coding Ninjas × Google Vibe2Ship Hackathon 2026
          </p>
          <div className="text-[10px] text-[#4A4A6A]">
            Powered by <span className="text-[#8B8BA7] font-medium">Gemini · Firebase · Firestore</span>
          </div>
        </div>
      </footer>
    </div>
  )
}
